global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['prometheus:9090']
# 
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']
# 
#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8080']
# 
#   - job_name: 'loki'
#     static_configs:
#       - targets: ['loki:3100']
# 
#   - job_name: 'crowdsec'
#     static_configs:
#       - targets: ['crowdsec:6060']
# 
#   - job_name: 'alloy'
#     static_configs:
#       - targets: ['alloy:12345']